database:   #数据库参数
  DbUsername: root
  DbPassword: root
  DbHost: localhost
  DbPort: 3366
  DbName: img
  DbConfig: charset=utf8&parseTime=True&loc=Local
server:  #web服务参数
  HttpPort: 8081
  HttpUsername: root
  HttpPassword: root@123
scanArgs:  #扫描参数
  StartPath: /Users/ld/Downloads/save/pic-lib/pic-new
  DeleteShow: true
  MoveFileShow: true
  ModifyDateShow: false
  RenameFileShow: true
  Md5Show: true
  DeleteAction: false
  MoveFileAction: false
  ModifyDateAction: false
  RenameFileAction: false
basic:
  ColorOutput: true   #日志是否输出彩色
cache:
  ImgCache: false   #是否要使用图片cache，会将新的记录插入数据库
  SyncTable: false    #会根据当前数据库匹配不上的记录删掉
  TruncateTable: false    #先truncate表
dump:
  PoolSize: 8   #单个照片处理的并行度
  Md5Retry: 3   #获取哈希值的重试次数
  Md5CountLength: 65536    # 1024 * 64
bak:
  BakStatEnable: false   #是否启用备份目录的统计
  StartPathBak: /Users/ld/Downloads/save/pic-lib-bak/pic-new
gis:
  key : abc   #amap的key
batch:
  IDInsertBatchSize: 1000   #img_database的查询批次
  IDDeleteBatchSize: 300    #img_database的删除批次
  GDUpdateBatchSize: 1000   #更新gis_database的批次






