database:   #数据库参数
  DbUsername: root
  DbPassword: root
  DbHost: host.docker.internal
  DbPort: 33060
  DbName: img
  DbConfig: charset=utf8&parseTime=True&loc=Local
server:  #web服务参数
  HttpPort: 8081
  HttpUsername: admin
  HttpPassword: admin
