database:
  DbUsername: root
  DbPassword: root
  DbHost: localhost
  DbPort: 3366
  DbName: img
  DbConfig: charset=utf8&parseTime=True&loc=Local
server:
  HttpPort: 8081
  HttpUsername: root
  HttpPassword: root@123
scanArgs:
  StartPath: /Users/ld/Downloads/save/pic-lib/pic-new
  DeleteShow: true
  MoveFileShow: true
  ModifyDateShow: false
  Md5Show: true
  DeleteAction: false
  MoveFileAction: false
  ModifyDateAction: false
basic:
  ColorOutput: true
cache:
  ImgCache: false   #会根据当前环境删除匹配不上的
  SyncTable: false
  TruncateTable: false
dump:
  PoolSize: 8
  Md5Retry: 3
  Md5CountLength: 65536    # 1024 * 64
bak:
  BakStatEnable: true
  StartPathBak: /Users/ld/Downloads/save/pic-lib-bak/pic-new
gis:
  key : abc
batch:
  IDInsertBatchSize: 5000
  IDDeleteBatchSize: 100






