database:
  Dbusername: root
  Dbpassword: root
  Dbhost: localhost
  Dbport: 3366
  Dbname: img
  Dbconfig: charset=utf8&parseTime=True&loc=Local
server:
  HttpPort: 8081
  HttpUsername: root
  HttpPassword: root@123
scan:
  StartPath: /Users/ld/Desktop/pic-new
  DeleteShow: true
  MoveFileShow: true
  ModifyDateShow: true
  Md5Show: true
  DeleteAction: false
  MoveFileAction: false
  ModifyDateAction: false
basic:
  ColorOutput: false


