database:
  DbUsername: root
  DbPassword: root
  DbHost: localhost
  DbPort: 3366
  DbName: img
  DbConfig: charset=utf8&parseTime=True&loc=Local
server:
  HttpPort: 8081
  HttpUsername: root
  HttpPassword: root@123
scan:
  StartPath: /Users/ld/Downloads/save/pic-lib/pic-new
  DeleteShow: true
  MoveFileShow: true
  ModifyDateShow: false
  Md5Show: true
  DeleteAction: false
  MoveFileAction: false
  ModifyDateAction: false
basic:
  ColorOutput: true
  ImgCache: false
  TruncateTable: false
bak:
  BakStatEnable: true
  StartPathBak: /Users/ld/Downloads/save/pic-lib-bak/pic-new





