services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    environment:
      IMG_PROCESS_CONFIG: /app/docker-config.yaml
      IMG_PROCESS_GIS_KEY: ${IMG_PROCESS_GIS_KEY:-}
      TZ: Asia/Shanghai
    ports:
      - "8081:8081"
    volumes:
      - ./docker/config.docker.yaml:/app/docker-config.yaml:ro
      - ./log:/app/log
      - ${IMG_PROCESS_SCAN_PATH:-/Users/ld/my-file/pic-lab}:/data/pic-lab
